version: "3.7"

services:
  node-red:
    image: nodered/node-red:latest
    container_name: node-red
    restart: unless-stopped
    env_file:
      - ./.env
    environment:
      - TZ=Asia/Jakarta
    devices:
      - /dev/ttyUSB0:/dev/ttyUSB0
    ports:
      - "1880:1880"
    networks:
      - node-red-net
    volumes:
      - ./data:/data
    group_add:
      - dialout

networks:
  node-red-net:
     name: smarthome_net
